import { RoomSnapshot, TLSocketRoom } from "@tldraw/sync-core";
import { TLRecord } from "@tldraw/tlschema";
import { AutoRouter, IRequest, error } from "itty-router";
const MAX_SNAPSHOT_BYTES = 5 * 1024 * 1024; // 5 MB guardrail to prevent costly writes
// Import the SINGLE SOURCE OF TRUTH schema from shared/tldrawSchema.ts
// Both client and server now use the exact same schema object generated by createTLSchemaFromUtils
import { schema } from "../../shared/tldrawSchema";

/**
 * Sanitize a room snapshot to remove invalid properties that cause validation errors.
 * This is needed to clean up data that was stored with older schema versions.
 * 
 * Specifically fixes:
 * - ValidationError: At instance.stylesForNextShape.tldraw:geo: Unexpected property
 */
function sanitizeRoomSnapshot(snapshot: RoomSnapshot | null): RoomSnapshot | null {
  if (!snapshot) return null;
  
  try {
    const snapshotAny = snapshot as any;
    
    // Check if there's a documents array (standard tldraw sync format)
    if (snapshotAny.documents && Array.isArray(snapshotAny.documents)) {
      for (const doc of snapshotAny.documents) {
        // Find instance records
        if (doc.state?.id?.startsWith('instance:')) {
          const stylesForNextShape = doc.state?.stylesForNextShape;
          if (stylesForNextShape && typeof stylesForNextShape === 'object') {
            // Remove invalid tldraw:geo style property (not a valid style key)
            if ('tldraw:geo' in stylesForNextShape) {
              console.log('🧹 Sanitizing invalid tldraw:geo from stylesForNextShape');
              delete stylesForNextShape['tldraw:geo'];
            }
          }
        }
      }
    }
    
    // Also check clock-based format (older snapshots)
    if (snapshotAny.clock !== undefined && snapshotAny.documents === undefined) {
      // This might be a different snapshot format - iterate over all keys
      for (const key of Object.keys(snapshotAny)) {
        if (key.startsWith('instance:')) {
          const instance = snapshotAny[key];
          if (instance?.stylesForNextShape && typeof instance.stylesForNextShape === 'object') {
            if ('tldraw:geo' in instance.stylesForNextShape) {
              console.log('🧹 Sanitizing invalid tldraw:geo from instance stylesForNextShape');
              delete instance.stylesForNextShape['tldraw:geo'];
            }
          }
        }
      }
    }
    
    return snapshot;
  } catch (err) {
    console.error('⚠️ Error sanitizing snapshot:', err);
    return snapshot; // Return original if sanitization fails
  }
}

// each whiteboard room is hosted in a DurableObject:
// https://developers.cloudflare.com/durable-objects/

// 🔧 NEW: Uses SQLite as source of truth for room snapshots (synchronous, guaranteed persistence)
// R2 is kept as optional backup/history (async, fire-and-forget)
// This matches tldraw's new persistence strategy for better reliability and lower memory usage
export class TldrawDurableObject {
  private r2: R2Bucket;
  // the room ID will be missing while the room is being initialized
  private roomId: string | null = null;
  // when we load the room from SQLite, we keep it here. it's a promise so we only ever
  // load it once.
  private roomPromise: Promise<TLSocketRoom<TLRecord, void>> | null = null;
  // Track if SQLite table has been initialized
  private sqliteInitialized: boolean = false;
  // Track active WebSocket connections for hibernation
  private activeConnections = new Set<WebSocket>();
  // Map sockets to session/room so hibernation lifecycle handlers can forward messages
  private socketSessions = new Map<
    WebSocket,
    { sessionId: string; room: TLSocketRoom<TLRecord, void> }
  >();
  // Track latest socket per session to prevent parallel connections
  private sessionSockets = new Map<string, WebSocket>();
  // Track last close time per session to apply reconnect backoff
  private sessionLastCloseAt = new Map<string, number>();
  private lastPersistAt: number | null = null;
  // Reconnect backoff window (ms)
  private static readonly RECONNECT_BACKOFF_MS = 2_000;
  // Minimum interval between persists (ms)
  private static readonly MIN_PERSIST_INTERVAL_MS = 10_000;

  constructor(private readonly ctx: DurableObjectState, env: Env) {
    this.r2 = env.TLDRAW_BUCKET;

    ctx.blockConcurrencyWhile(async () => {
      this.roomId = ((await this.ctx.storage.get("roomId")) ?? null) as
        | string
        | null;
      
      // Initialize SQLite table synchronously
      this.initializeSQLiteTable();
    });
  }

  // Initialize SQLite table for room snapshots
  private initializeSQLiteTable() {
    if (this.sqliteInitialized) return;
    
    try {
      // Create table if it doesn't exist
      // Store snapshot as JSON text - SQLite handles this efficiently
      this.ctx.storage.transactionSync(() => {
        this.ctx.storage.sql.exec(`
          CREATE TABLE IF NOT EXISTS room_snapshots (
            room_id TEXT PRIMARY KEY,
            snapshot TEXT NOT NULL,
            schema_version TEXT,
            saved_at INTEGER NOT NULL,
            updated_at INTEGER NOT NULL
          )
        `);
        
        // Create index for faster lookups
        this.ctx.storage.sql.exec(`
          CREATE INDEX IF NOT EXISTS idx_room_snapshots_room_id 
          ON room_snapshots(room_id)
        `);
      });
      
      this.sqliteInitialized = true;
      console.log("✅ SQLite table initialized for room snapshots");
    } catch (err) {
      console.error("❌ Failed to initialize SQLite table:", err);
      // Continue anyway - will fall back to R2 if SQLite fails
    }
  }

  private readonly router = AutoRouter({
    catch: (e) => {
      console.log(e);
      return error(e);
    },
  })
    // when we get a connection request, we stash the room id if needed and handle the connection
    .get("/api/connect/:roomId", async (request) => {
      if (!this.roomId) {
        await this.ctx.blockConcurrencyWhile(async () => {
          await this.ctx.storage.put("roomId", request.params.roomId);
          this.roomId = request.params.roomId;
        });
      }
      return this.handleConnect(request);
    })
    // Handle delete room data request
    .post("/delete", async () => {
      await this.deleteRoomData();
      return new Response(
        JSON.stringify({ success: true, message: "Room data deleted" }),
        {
          status: 200,
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
    });

  // `fetch` is the entry point for all requests to the Durable Object
  fetch(request: Request): Response | Promise<Response> {
    return this.router.fetch(request);
  }

  // what happens when someone tries to connect to this room?
  async handleConnect(request: IRequest) {
    // extract query params from request
    const sessionId = request.query.sessionId as string;
    if (!sessionId) return error(400, "Missing sessionId");

    // Reconnect backoff: if the same session closed recently, reject fast
    const lastClose = this.sessionLastCloseAt.get(sessionId);
    if (
      lastClose &&
      Date.now() - lastClose < TldrawDurableObject.RECONNECT_BACKOFF_MS
    ) {
      console.warn("⚠️ Reconnect backoff: rejecting rapid reconnect", {
        sessionId,
        roomId: this.roomId,
      });

      // Accept and immediately close with rate limit code so client can back off
      const { 0: clientWebSocket, 1: serverWebSocket } = new WebSocketPair();
      this.ctx.acceptWebSocket(serverWebSocket);
      // NOTE: Do NOT reset sessionLastCloseAt here — resetting on every rejection
      // makes the backoff permanent (the timer never expires). Only real connection
      // closes should set this timestamp.
      try {
        serverWebSocket.close(
          4001,
          `RATE_LIMITED:${TldrawDurableObject.RECONNECT_BACKOFF_MS}`
        );
      } catch {
        // ignore
      }
      return new Response(null, { status: 101, webSocket: clientWebSocket });
    }

    // Create the websocket pair for the client
    const { 0: clientWebSocket, 1: serverWebSocket } = new WebSocketPair();

    // Use acceptWebSocket to enable hibernation - this allows the Durable Object
    // to hibernate when all WebSockets close, reducing duration charges
    this.ctx.acceptWebSocket(serverWebSocket);
    this.activeConnections.add(serverWebSocket);

    // Enforce single live socket per sessionId - close any previous one
    const existing = this.sessionSockets.get(sessionId);
    if (existing && existing !== serverWebSocket) {
      try {
        existing.close(4000, "replaced_by_new_connection");
      } catch {
        // ignore
      }
      this.cleanupSocket(existing);
    }
    this.sessionSockets.set(sessionId, serverWebSocket);

    // load the room, or retrieve it if it's already loaded
    const room = await this.getRoom();

    // Log room info
    console.log("🔍 Server connecting client:", {
      sessionId,
      roomId: this.roomId,
      hasRoom: !!room,
    });

    try {
      // Log schema info before connecting
      const schemaAny = schema as any;
      console.log("🔍 Server schema info before connect:", {
        hasSchema: !!schema,
        schemaShapes: schemaAny?.types?.shape
          ? Object.keys(schemaAny.types.shape).slice(0, 20)
          : schemaAny?.shapes
          ? Object.keys(schemaAny.shapes).slice(0, 10)
          : [],
        // Try to get protocol version from schema if available
        schemaVersion: schemaAny?.version,
        schemaSequence: schemaAny?.storeMigrations?.sequence?.length,
      });

      // connect the client to the room
      room.handleSocketConnect({ sessionId, socket: serverWebSocket });
      console.log("✅ Server connected client to room");
      this.socketSessions.set(serverWebSocket, { sessionId, room });
    } catch (err) {
      console.error("❌ Server error connecting client:", err);
      console.error("❌ Error details:", {
        message: err instanceof Error ? err.message : String(err),
        name: err instanceof Error ? err.name : "Unknown",
        stack: err instanceof Error ? err.stack : "No stack",
      });

      // If CLIENT_TOO_OLD error, try clearing room data and reconnecting
      const errorMessage = err instanceof Error ? err.message : String(err);
      if (
        errorMessage.includes("CLIENT_TOO_OLD") ||
        errorMessage.includes("too old")
      ) {
        console.warn(
          "⚠️ CLIENT_TOO_OLD detected - clearing room data and starting fresh"
        );
        try {
          await this.deleteRoomData();
          // Reset room promise to create a fresh room
          this.roomPromise = null;
          // Try connecting again with fresh room
          const freshRoom = await this.getRoom();
          freshRoom.handleSocketConnect({ sessionId, socket: serverWebSocket });
          console.log("✅ Reconnected with fresh room after CLIENT_TOO_OLD");
          this.socketSessions.set(serverWebSocket, {
            sessionId,
            room: freshRoom,
          });
        } catch (retryErr) {
          console.error("❌ Failed to recover from CLIENT_TOO_OLD:", retryErr);
        }
      }
    }

    // return the websocket connection to the client
    return new Response(null, { status: 101, webSocket: clientWebSocket });
  }

  getRoom() {
    const roomId = this.roomId;
    if (!roomId) throw new Error("Missing roomId");

    if (!this.roomPromise) {
      this.roomPromise = (async () => {
        // 🔧 NEW: Load from SQLite synchronously (source of truth)
        let initialSnapshot: RoomSnapshot | undefined = undefined;
        
        try {
          // Load from SQLite synchronously - this is fast and guaranteed
          const sqliteSnapshot = this.ctx.storage.transactionSync(() => {
            const result = this.ctx.storage.sql.exec<{
              snapshot: string;
              schema_version: string | null;
            }>(
              `SELECT snapshot, schema_version FROM room_snapshots WHERE room_id = ?`,
              roomId
            );
            
            const row = result.one();
            return row ? JSON.parse(row.snapshot) as RoomSnapshot : null;
          });

          if (sqliteSnapshot) {
            console.log("📦 Loaded room snapshot from SQLite:", {
              roomId,
              hasSnapshot: !!sqliteSnapshot,
              snapshotKeys: sqliteSnapshot ? Object.keys(sqliteSnapshot).slice(0, 5) : [],
            });
            // 🧹 Sanitize snapshot to remove invalid properties (e.g., tldraw:geo)
            initialSnapshot = sanitizeRoomSnapshot(sqliteSnapshot) ?? undefined;
          } else {
            // No SQLite data - try migrating from R2 (one-time migration)
            console.log("💡 No SQLite snapshot found, checking R2 for migration...");
            const roomFromBucket = await this.r2.get(`rooms/${roomId}`);
            if (roomFromBucket) {
              try {
                const snapshot = (await roomFromBucket.json()) as RoomSnapshot;
                const snapshotAny = snapshot as any;
                const currentSchemaVersion = (schema as any)?.version;
                const snapshotSchemaVersion =
                  snapshotAny?.schemaVersion ||
                  snapshotAny?._metadata?.schemaVersion;

                // Validate schema version before migrating
                if (!snapshotSchemaVersion || snapshotSchemaVersion !== currentSchemaVersion) {
                  console.warn(
                    "⚠️ R2 snapshot incompatible - skipping migration",
                    {
                      hasSchemaVersion: !!snapshotSchemaVersion,
                      matches: snapshotSchemaVersion === currentSchemaVersion,
                    }
                  );
                  // Delete incompatible R2 snapshot
                  try {
                    await this.r2.delete(`rooms/${roomId}`);
                  } catch {}
                  initialSnapshot = undefined;
                } else {
                  // Migrate from R2 to SQLite
                  console.log("🔄 Migrating room snapshot from R2 to SQLite...");
                  // 🧹 Sanitize snapshot to remove invalid properties (e.g., tldraw:geo)
                  const sanitizedSnapshot = sanitizeRoomSnapshot(snapshot);
                  initialSnapshot = sanitizedSnapshot ?? undefined;
                  
                  // Persist sanitized version to SQLite immediately (synchronous, guaranteed)
                  if (sanitizedSnapshot) {
                    this.persistToSQLite(roomId, sanitizedSnapshot);
                  }
                  
                  console.log("✅ Migration complete - room now in SQLite");
                }
              } catch (err) {
                console.error("❌ Failed to migrate from R2:", err);
                initialSnapshot = undefined;
              }
            }
          }
        } catch (sqliteErr) {
          console.error("❌ SQLite load failed, falling back to R2:", sqliteErr);
          // Fallback to R2 if SQLite fails
          const roomFromBucket = await this.r2.get(`rooms/${roomId}`);
          if (roomFromBucket) {
            try {
              const snapshot = (await roomFromBucket.json()) as RoomSnapshot;
              const snapshotAny = snapshot as any;
              const currentSchemaVersion = (schema as any)?.version;
              const snapshotSchemaVersion =
                snapshotAny?.schemaVersion ||
                snapshotAny?._metadata?.schemaVersion;

              if (snapshotSchemaVersion === currentSchemaVersion) {
                // 🧹 Sanitize snapshot to remove invalid properties (e.g., tldraw:geo)
                const sanitizedSnapshot = sanitizeRoomSnapshot(snapshot);
                initialSnapshot = sanitizedSnapshot ?? undefined;
                // Try to persist sanitized version to SQLite for next time
                try {
                  if (sanitizedSnapshot) {
                    this.persistToSQLite(roomId, sanitizedSnapshot);
                  }
                } catch {}
              }
            } catch (err) {
              console.error("❌ R2 fallback also failed:", err);
            }
          }
        }

        // create a new TLSocketRoom. This handles all the sync protocol & websocket connections.
        // it's up to us to persist the room state to R2 when needed though.
        const schemaAny = schema as any;
        console.log("🔍 Creating TLSocketRoom:", {
          roomId,
          hasInitialSnapshot: !!initialSnapshot,
          schemaType: typeof schema,
          schemaShapes: schemaAny?.types?.shape
            ? Object.keys(schemaAny.types.shape).slice(0, 20)
            : [],
          schemaVersion: schemaAny?.version,
          schemaSequence: schemaAny?.storeMigrations?.sequence?.length,
        });

        const room = new TLSocketRoom<TLRecord, void>({
          schema: schema as any, // Type assertion needed - schema is TLSchema but TLSocketRoom expects StoreSchema
          initialSnapshot,
          onDataChange: () => {
            // 🔧 NEW: Persist to SQLite synchronously (guaranteed, immediate error detection)
            // R2 backup is optional and async (fire-and-forget)
            if (this.roomId) {
              try {
                const snapshot = room.getCurrentSnapshot();
                this.persistToSQLite(this.roomId, snapshot);
                // Also backup to R2 (async, optional)
                this.schedulePersistToR2().catch(() => {
                  // Silently fail - R2 is just backup
                });
              } catch (err) {
                console.error("❌ Failed to persist to SQLite:", err);
                // Alert connected clients if persistence fails
                // (In production, you might want to notify clients)
              }
            }
          },
        });

        // Add error handler to room if available
        if (room && typeof (room as any).onError === "function") {
          (room as any).onError((error: Error) => {
            console.error("🔴 TLSocketRoom error:", {
              error: error.message,
              stack: error.stack,
              roomId,
              schemaVersion: schemaAny?.version,
              schemaShapes: schemaAny?.types?.shape
                ? Object.keys(schemaAny.types.shape)
                : [],
            });
          });
        }

        // Add sync error handler to catch INVALID_RECORD errors
        if (room && typeof (room as any).onSyncError === "function") {
          (room as any).onSyncError((error: any) => {
            console.error("🔴 TLSocketRoom sync error:", {
              error: error?.message || String(error),
              errorType: error?.type,
              errorCode: error?.code,
              roomId,
              schemaVersion: schemaAny?.version,
            });
            // If it's an INVALID_RECORD error, log more details
            if (
              error?.message?.includes("INVALID_RECORD") ||
              error?.code === "INVALID_RECORD"
            ) {
              console.error(
                "⚠️ INVALID_RECORD detected - this may indicate schema mismatch or corrupted data"
              );
              console.error("   Consider clearing room data if this persists");
            }
          });
        }

        return room;
      })();
    }

    return this.roomPromise;
  }

  // 🔧 NEW: Persist to SQLite synchronously (source of truth)
  // This is guaranteed to work or throw an error immediately
  private persistToSQLite(roomId: string, snapshot: RoomSnapshot) {
    try {
      const schemaAny = schema as any;
      const snapshotWithMetadata = {
        ...snapshot,
        schemaVersion: schemaAny?.version,
        _metadata: {
          savedAt: new Date().toISOString(),
          protocolVersion: "4.1.2",
          schemaVersion: schemaAny?.version,
        },
      };
      const snapshotJson = JSON.stringify(snapshotWithMetadata);
      const now = Date.now();

      // Persist synchronously to SQLite
      this.ctx.storage.transactionSync(() => {
        this.ctx.storage.sql.exec(
          `INSERT OR REPLACE INTO room_snapshots 
           (room_id, snapshot, schema_version, saved_at, updated_at) 
           VALUES (?, ?, ?, ?, ?)`,
          roomId,
          snapshotJson,
          schemaAny?.version || null,
          now,
          now
        );
      });

      console.log("💾 Persisted to SQLite (source of truth):", {
        roomId,
        snapshotBytes: new TextEncoder().encode(snapshotJson).byteLength,
      });
    } catch (err) {
      console.error("❌ SQLite persistence failed:", err);
      throw err; // Re-throw so caller knows persistence failed
    }
  }

  // R2 backup (optional, async, fire-and-forget) - throttled to every 10 seconds
  schedulePersistToR2 = async () => {
    if (!this.roomPromise || !this.roomId) return;
    const now = Date.now();
    // Enforce minimum persist interval to reduce churn
    if (
      this.lastPersistAt &&
      now - this.lastPersistAt < TldrawDurableObject.MIN_PERSIST_INTERVAL_MS
    ) {
      return;
    }
    this.lastPersistAt = now;
    const room = await this.getRoom();

    // convert the room to JSON and upload it to R2 (backup only)
    const snapshot = room.getCurrentSnapshot();
    const schemaAny = schema as any;
    const snapshotWithMetadata = {
      ...snapshot,
      schemaVersion: schemaAny?.version,
      _metadata: {
        savedAt: new Date().toISOString(),
        protocolVersion: "4.1.2",
        schemaVersion: schemaAny?.version,
      },
    };
    const snapshotJson = JSON.stringify(snapshotWithMetadata);
    const snapshotBytes = new TextEncoder().encode(snapshotJson).byteLength;
    if (snapshotBytes > MAX_SNAPSHOT_BYTES) {
      console.warn("⚠️ Snapshot too large for R2 backup - skipping", {
        roomId: this.roomId,
        snapshotBytes,
        maxBytes: MAX_SNAPSHOT_BYTES,
      });
      return;
    }

    // Fire-and-forget R2 backup
    this.r2.put(`rooms/${this.roomId}`, snapshotJson).catch((err) => {
      // Silently fail - R2 is just backup, SQLite is source of truth
      console.warn("⚠️ R2 backup failed (non-critical):", err);
    });
  };

  // Helper method to delete room data (for clearing old incompatible data)
  async deleteRoomData() {
    if (!this.roomId) return;
    try {
      // Delete from SQLite (source of truth)
      this.ctx.storage.transactionSync(() => {
        this.ctx.storage.sql.exec(
          `DELETE FROM room_snapshots WHERE room_id = ?`,
          this.roomId!
        );
      });
      console.log(`🗑️ Deleted room data from SQLite for: ${this.roomId}`);
      
      // Also delete from R2 backup
      try {
        await this.r2.delete(`rooms/${this.roomId}`);
        console.log(`🗑️ Deleted room data from R2 for: ${this.roomId}`);
      } catch (r2Err) {
        // Non-critical - R2 is just backup
        console.warn("⚠️ Failed to delete from R2 (non-critical):", r2Err);
      }
      
      // Reset room promise so it creates a fresh room
      this.roomPromise = null;
    } catch (err) {
      console.error(`❌ Failed to delete room data: ${err}`);
    }
  }

  // Hibernation support: route messages to TLSocketRoom when Cloudflare delivers them
  webSocketMessage(ws: WebSocket, event: MessageEvent) {
    const session = this.socketSessions.get(ws);
    if (!session) {
      console.warn("⚠️ Received message for unknown socket (possibly stale)", {
        roomId: this.roomId,
      });
      return;
    }

    try {
      const data = (event as any)?.data ?? event;
      session.room.handleSocketMessage(session.sessionId, data as any);
    } catch (err) {
      console.error("🔴 WebSocket message handling failed:", {
        error: err instanceof Error ? err.message : String(err),
        roomId: this.roomId,
        sessionId: session.sessionId,
      });
      session.room.handleSocketError(session.sessionId);
    }
  }

  // Hibernation support: Called when a WebSocket closes
  // This allows the Durable Object to hibernate when all connections close,
  // which stops accumulating duration charges
  webSocketClose(ws: WebSocket, event: CloseEvent) {
    const session = this.socketSessions.get(ws);
    console.log("🔌 WebSocket closed, object may hibernate:", {
      code: event.code,
      reason: event.reason,
      wasClean: event.wasClean,
      roomId: this.roomId,
      remainingConnections: this.activeConnections.size - 1,
      sessionId: session?.sessionId,
    });

    if (session) {
      try {
        session.room.handleSocketClose(session.sessionId);
      } catch (err) {
        console.error("⚠️ Failed to notify room of socket close:", err);
      }
      // Track last close to enforce reconnect backoff
      this.sessionLastCloseAt.set(session.sessionId, Date.now());
    }

    this.cleanupSocket(ws);

    // If this was the last connection, ensure we persist the room state
    // before hibernation (SQLite is already persisted, but backup to R2)
    if (this.activeConnections.size === 0 && this.roomPromise && this.roomId) {
      console.log(
        "💤 Last connection closed, room already persisted to SQLite"
      );
      // Optional: Final R2 backup before hibernation (async, non-critical)
      this.ctx.waitUntil(
        (async () => {
          try {
            const room = await this.getRoom();
            const snapshot = room.getCurrentSnapshot();
            const schemaAny = schema as any;
            const snapshotWithMetadata = {
              ...snapshot,
              schemaVersion: schemaAny?.version,
              _metadata: {
                savedAt: new Date().toISOString(),
                protocolVersion: "4.1.2",
                schemaVersion: schemaAny?.version,
              },
            };
            const snapshotJson = JSON.stringify(snapshotWithMetadata);
            const snapshotBytes = new TextEncoder().encode(
              snapshotJson
            ).byteLength;
            if (snapshotBytes > MAX_SNAPSHOT_BYTES) {
              console.warn(
                "⚠️ Final R2 backup skipped: snapshot too large",
                {
                  roomId: this.roomId,
                  snapshotBytes,
                  maxBytes: MAX_SNAPSHOT_BYTES,
                }
              );
              return;
            }

            // Fire-and-forget R2 backup
            await this.r2.put(`rooms/${this.roomId}`, snapshotJson);
            console.log("✅ Final R2 backup completed (optional)", {
              roomId: this.roomId,
              snapshotBytes,
            });
          } catch (err) {
            // Non-critical - SQLite is source of truth
            console.warn("⚠️ Final R2 backup failed (non-critical):", err);
          }
        })()
      );
    }
  }

  // Hibernation support: Called when a WebSocket error occurs
  webSocketError(ws: WebSocket, error: Error) {
    const session = this.socketSessions.get(ws);
    console.error("🔴 WebSocket error:", {
      error: error.message,
      roomId: this.roomId,
      sessionId: session?.sessionId,
    });

    if (session) {
      try {
        session.room.handleSocketError(session.sessionId);
      } catch (err) {
        console.error("⚠️ Failed to notify room of socket error:", err);
      }
    }
    this.cleanupSocket(ws);
  }

  private cleanupSocket(ws: WebSocket) {
    this.activeConnections.delete(ws);
    const session = this.socketSessions.get(ws);
    if (session) {
      this.socketSessions.delete(ws);
      const current = this.sessionSockets.get(session.sessionId);
      if (current === ws) {
        this.sessionSockets.delete(session.sessionId);
      }
    }
  }
}
